[package]
name = "anet-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
log = { workspace = true }
env_logger = { workspace = true }
dotenvy = "0.15"

poem = "3.1.8"
poem-openapi = { version = "5.1.12", features = ["swagger-ui", "uuid"] }

sea-orm = { version = "2.0.2", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
sea-orm-migration = "2.0.2"
uuid = { version = "1.10", features = ["serde", "v4"] }
clap = { workspace = true, features = ["derive"] }
ed25519-dalek = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
chrono = "0.4.43"
rpassword = "7.4.0"
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
bcrypt = "0.19.0"
bytes = {workspace = true}
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
ipnet = { workspace = true }
toml = { workspace = true }

anet-common = { path = "../anet-common", features = ["poem"] }

[[bin]]
name = "anet-auth"
path = "src/main.rs"
